### ISSUE TITLE
Ground on BQ76952

### ISSUE THREAD

**Issue by JochenKr** [LibreSolar/bms-16s100-sc#11]
The ground loop around the IC can be improved.
![image](https://user-images.githubusercontent.com/100796228/156425360-3fb60c43-ff70-48e2-aa9e-1a3f14f904de.png)

the best would be to have a solid GND plane below the IC. This seems not to be easy.
An improvement could be to put TS3 signal to bottom layer. By this there is a solid connection of GND on top layer possible,
By slightly moving RST_SHUT and TEMP4 it is possible to add two additional vias in that area to connect the planes.
![image](https://user-images.githubusercontent.com/100796228/156426203-3df2c48e-bfe4-4ac0-ab11-0056f6a3ac4d.png)

**Comment by martinjaeger** [comment]
Good spot. I also realized that the routing around the IC with the many traces in the bottom layer is not ideal. But also didn't want to go for a 4-layer PCB just because of that. I'll try to move things around a bit so that the top plane bridges the gaps created by the traces in the bottom plane better.

**Comment by martinjaeger** [comment]
After watching [this amazing video](https://www.youtube.com/watch?v=ySuUZEjARPY&ab_channel=Altium) as recommended by @Light411 I finally decided to switch to a 4-layer PCB. I thought I'd get away with the cheaper 2-layer version, but routing around the IC proves to be really difficult. I guess the small cost increase will be worth the improved performance.

**Comment by Light411** [comment]
Super happy that it was helpful ! I'm sure it will greatly improve the ground loops issues. 
What layer stack-up will you choose ? Will you do 

- Signal 
- Ground 
- Ground 
- Signal 

as suggested by Rick, with a routed VCC ?

**Comment by martinjaeger** [comment]
Yes, exactly. I was previously mostly using:

- Signal
- Ground
- VCC (3V3)
- Signal

But after watching his video it seems to make more sense to have two GND layers and a routed VCC. Maybe the VCC can be partly flooded on the bottom layer, otherwise there would be very few traces only.
