### ISSUE TITLE
Gate protection diodes of Mosfets

### ISSUE THREAD

**Issue by JochenKr** [LibreSolar/bms-16s100-sc#12]
The protection Z-diodes and pulldown resistors might not help against transients, as they are not close to the gates of the Mosfets.
For the case that transients occur, it might make sense to have a second pair of z-diodes for the left side Fets.

![image](https://user-images.githubusercontent.com/100796228/156427073-3e894e4e-54a8-4605-8b7a-6d640298d1f2.png)

**Comment by martinjaeger** [comment]
Done. Will be updated in next commit.

![image](https://user-images.githubusercontent.com/17674105/157894251-7d20079f-b778-40e8-8031-333314be11ca.png)
