### ISSUE TITLE
Tracks running under Y1 resonator

### ISSUE THREAD

**Issue by Light411** [LibreSolar/bms-16s100-sc#17]
I do see two tracks running under Y1. I think it is possible to pull it a bit apart from the MCU to make sure there is no tracks beneath it. 
I've read that the good practice is to have ground keepout under the crystal / resonator, with a ground island dedicated to the resonator and a via fence surrounding this ground island. 
This helps protecting surrounding signals and prevent unwanted capacitance to disturb the crystal. 
I would also suggest to have symmetrical tracks for Y1 to the MCU. 

![image](https://user-images.githubusercontent.com/22010135/156735839-78601713-8123-4071-ae1d-8a859a8aaaf6.png)
This is one of my most recent attempts at routing a crystal and taking these consideration into account.

**Comment by martinjaeger** [comment]
Thanks for the valid comment. I've made the two traces with equal distances now and added some GND guard around the resonator. 

![image](https://user-images.githubusercontent.com/17674105/158354250-cd64ada3-c746-4dad-8dde-952b5ab087af.png)

Completely removing all traces close to below the resonator was not easily possible, but as the board has 4 layers now I don't think there will be any cross-talk through the layers.
