### ISSUE TITLE
How to better stitch the ground plane ?

### ISSUE THREAD

**Issue by Light411** [LibreSolar/bms-16s100-sc#18]
I do have a concern regarding the bottom tracks that kind of break your ground plane apart. 
I understand the routing constraints here, as it is a 2 layer PCB, but you should consider adding more via stitching from top to bottom to permit return currents to cross this ground plane discontinuity.

![image](https://user-images.githubusercontent.com/22010135/156736810-29b0dd98-7ee9-45fa-9925-359788571b4f.png)

**Comment by martinjaeger** [comment]
Board is now 4-layer with two inner layers being GND. There should not be any issue with interrupted GND plane anymore.
