### ISSUE TITLE
Choice of ESP32 variant

### ISSUE THREAD

**Issue by EarthLord** [LibreSolar/bms-16s100-sc#7]
C3 Mini module of ESP32 is chosen. Any reason for C3 vs say S2?

**Comment by martinjaeger** [comment]
It's mainly due to space constraints. The "larger" ESPs are not available with a small footprint module. And compared to the STM32G0B1 the ESP32-C3 is still more powerful.

Would you have any particular use case which requires an ESP32-S2?

**Comment by martinjaeger** [comment]
I just see that the S2 doesn't even have Bluetooth, which is the main reason for me to have ESP32 support.

Also I kind of like that the ESP32-C3 has a RISC-V core :)

**Comment by EarthLord** [comment]
Sounds good. Just asked to understand your decision process. Yes, was quite a pleasant surprise when ESP32 C3 came out with a RISC-V ISA based core.
